class GOST341194:
    def __init__(self, data: bytes=..., sbox: str=...) -> None: ...

    @property
    def digest_size(self) -> int: ...

    def copy(self) -> "GOST341194": ...

    def update(self, data: bytes) -> None: ...

    def digest(self) -> bytes: ...

    def hexdigest(self) -> str: ...
