def pad_size(data_size: int, blocksize: int) -> int: ...


def pad1(data: bytes, blocksize: int) -> bytes: ...


def pad2(data: bytes, blocksize: int) -> bytes: ...


def pad3(data: bytes, blocksize: int) -> bytes: ...
