class GOST341194:
    def __init__(self, data: bytes=..., sbox: str=...) -> None: ...

    @property
    def digest_size(self) -> int: ...

    def copy(self) -> "GOST341194": ...

    def update(self, data: bytes) -> None: ...

    def digest(self) -> bytes: ...

    def hexdigest(self) -> str: ...


def new(data: bytes=..., sbox: str=...) -> GOST341194: ...


def pbkdf2(password: bytes, salt: bytes, iterations: int, dklen: int) -> bytes: ...
