def wrap_gost(ukm: bytes, kek: bytes, cek: bytes, sbox: str = ...) -> bytes: ...


def unwrap_gost(kek: bytes, data: bytes, sbox: str = ...) -> bytes: ...


def wrap_cryptopro(ukm: bytes, kek: bytes, cek: bytes, sbox: str = ...) -> bytes: ...


def unwrap_cryptopro(kek: bytes, data: bytes, sbox: str = ...) -> bytes: ...
