PYTHON ?= python

test:
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost28147
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost28147_mac
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost341194
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost34112012
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3410
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3410_vko
	PYTHONPATH=.. $(PYTHON) -m unittest test_wrap
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3412
