PYTHON ?= python

test:
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost28147
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost28147_mac
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3411_94
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3411_2012
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3410
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3410_vko
	PYTHONPATH=.. $(PYTHON) -m unittest test_wrap
	PYTHONPATH=.. $(PYTHON) -m unittest test_gost3412
